on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build_css:
    runs-on: ubuntu-latest
    env:
      source: public/dist/assets
      destination: assets/website-2021-dev/pr-${{ github.event.number }}/
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v5
        with:
          ref: ${{github.event.pull_request.head.ref}}
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '16'

      - name: Install npm modules
        run: npm install

      - name: compile assets
        run: npm run build

      - name: Upload to cdn-dev.w3.org bucket
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run:
          aws s3 sync --no-progress ${{ env.source }} s3://cdn-dev.w3.org/${{ env.destination }}

      - name: Add comment to PR
        uses: actions/github-script@v8
        if: ${{ github.event.action == 'opened'}}
        env:
          COMPOSER: 'composer require w3c/website-templates-bundle:dev-${{ github.ref }}'
          ASSETS: 'ASSETS_WEBSITE_2021=https://www-dev.w3.org/${{ env.destination }}/'
          BODY_TEXT: 'Assets published to https://www-dev.w3.org/${{ env.destination }}\n\nLoad in your application via:\n\n${{ env.COMPOSER }}\n\n${{ env.ASSETS }}'
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              issue_number: context.issue.number,
              repo: context.repo.repo,
              body: process.env.BODY_TEXT
            })
